"""Built-in defaults (lowest precedence)."""

from __future__ import annotations

DEFAULT_API_HOST = "127.0.0.1"
DEFAULT_API_PORT = 7070
DEFAULT_API_URL = f"http://{DEFAULT_API_HOST}:{DEFAULT_API_PORT}"

DEFAULT_POOL_NAME = "default"
DEFAULT_IMAGE = "python:3.12-slim"
DEFAULT_SANDBOX_TIMEOUT_SECONDS = 3600
DEFAULT_MAX_SANDBOX_TIMEOUT_SECONDS = 24 * 3600
DEFAULT_CREATE_TIMEOUT_SECONDS = 900.0

DEFAULT_WORKER_CPUS = 8
DEFAULT_WORKER_MEMORY = "32GB"
DEFAULT_WORKER_DISK_GB = 100
DEFAULT_WORKER_RESERVE_CPUS = 1.0
DEFAULT_WORKER_RESERVE_MEMORY = "2GB"
DEFAULT_MIN_WORKERS = 0
DEFAULT_MAX_WORKERS = 4
DEFAULT_IDLE_TTL_SECONDS = 900

DEFAULT_MAX_COMMAND_OUTPUT_BYTES = 4 * 1024 * 1024
DEFAULT_MAX_UPLOAD_BYTES = 512 * 1024 * 1024
DEFAULT_MAX_DOWNLOAD_BYTES = 512 * 1024 * 1024

DEFAULT_RECONCILE_INTERVAL_SECONDS = 10.0
DEFAULT_HEALTH_FAILURES_BEFORE_LOST = 6
DEFAULT_WORKER_PROVISION_TIMEOUT_SECONDS = 1800.0
DEFAULT_IDEMPOTENCY_TTL_SECONDS = 24 * 3600

DEFAULT_PROXY_URL_TTL_SECONDS = 3600

WORKER_PORT = 9417
WORKER_HOST = "127.0.0.1"

SANDBOX_NETWORK_NAME = "sandboxpilot"
SANDBOX_NETWORK_SUBNET = "10.211.0.0/16"

DISK_PRESSURE_MIN_FREE_BYTES = 10 * 1024**3
DISK_PRESSURE_MIN_FREE_FRACTION = 0.10
